version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  shortener:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: shortener_container
    ports:
      - "8080:8080"
      - "3200:3200"
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  pgdata:
    driver: local